services:
  - type: web
    name: rag-document-qa-bot
    runtime: python
    rootDir: rag-backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CHAT_MODEL
        value: cohere/north-mini-code:free
      - key: ALLOWED_ORIGINS
        value: http://localhost:4200